---
build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.17'
labels:
  org.opencontainers.image.title: 'Home Assistant App: Red Reactor Monitor'
  org.opencontainers.image.description: 'Red Reactor Battery Monitoring service.'
  org.opencontainers.image.source: 'https://github.com/mreditor97/homeassistant-apps'
  org.opencontainers.image.licenses: 'MIT'
