---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    name: CI
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@4452cb5bbe212770db7d858091d2e8ab09a4f783  # main
